### ISSUE TITLE
DevilutionX 1.4.1

### ISSUE THREAD

**Issue by AnDrePLGit** [SoundChaser83/devilutionx-apocrypha#9]
Is there a way to upgrade at least to DevilutionX 1.4.0 so that Gillian's stash would be available?
Also ShowItemLabels option would be nice :)

**Comment by SoundChaser83** [comment]
You should be able to see item labels by holding Alt, and you can also set labels to be always on by toggling with right Ctrl. Or are you referring to a different feature that I'm not familiar with?

As for Gillian's stash, it's possible but very difficult and time-consuming for me to upgrade Apocrypha to DevilutionX 1.4.1 since I'm doing this all by myself, and I'm still very new to coding in general. I could re-enable the Cornerstone so that you can transfer items between characters the old-fashioned way, but that would bring back a method of duping which I'd be unhappy with. I can't promise that anything will change soon, but it's something I'll think about going forward. I appreciate your comment though!

**Comment by AnDrePLGit** [comment]
I didn't know about right Ctrl (its doing exactly as ShowItemLabels in .ini) - thanks :)))
For me stash is mainly useful to hoard gold (5k limit for 1 inventory space sucks) and to not drop items on town floor. I hate that it is shared among characters (gold) but better this than nothing. Anyway, if you can add this, would be great, but without it, it seems that you done very good work - i have lots of fun playing your mod.

**Comment by SoundChaser83** [comment]
I'm glad to hear you're still enjoying the mod nonetheless! To be fully transparent, my original idea for this mod was to make it feel closer to a roguelike, and I'm also a speedrunner so I thought it would be fun to make a mod of the game that felt more balanced and fun for speedrunning (I don't care about the vanilla leaderboards; it's just a fun run, and even more fun if the game is balanced). This is why I haven't really prioritized the stash: I usually play a single character for a very short period of time and then delete it/start over. Eventually I thought it would be nice to extend my balance changes to the rest of the game and make nightmare/hell more fun while also making it more engaging to fully gear up a character, and having a stash would definitely be useful for that. It's just a lot of work for a coding noob like myself. But hey, if anyone wants to make a fork of Apocrypha and add the stash in, they're more than welcome to do that!
